### ISSUE TITLE
knowitop-checklist documentation

### ISSUE THREAD

**Issue by otto2018** [knowitop/knowitop-checklist#1]
Dear support,

Could you please, explain further what is the use of this module?

Thank you

**Comment by vbkunin** [comment]
Hi, @otto2018,
You can see the demo on YouTube: https://youtu.be/vQ2FlFz3fCI. If you'll decide to use this module, you'll have to install [knowitop-template-base](https://github.com/knowitop/knowitop-template-base) because of dependencies between them.
